### ISSUE TITLE
Make code compatible with python 3.

### ISSUE THREAD

**Issue by ymcasky** [COGMAR/RotEqNet#1]
Hi, when I run mnist_test.py
It occur an error :grinning: 
RuntimeError: argument 1 (padding) must be tuple of int but got tuple of (float, float)

Can you tell me how to fix this problem? Thanks!

**Comment by ghost** [comment]
Hi,

Could you provide the full trace stack?

Thanks!

**Comment by ymcasky** [comment]
Thanks for your reply.
It is the version conflict between py27&py3.x.
I can run your code successfully in py27.
In py3.x,  RotConv(1, 6, [9, 9], 1, 9 / 2, n_angles=17, mode=1) should be
RotConv(1, 6, [9, 9], 1, 9 // 2, n_angles=17, mode=1).
The final accuracy both achieve ~1.0.  : )

**Comment by waldeland** [comment]
Yeah, the code was developed for python 2.7. 
I will look into your proposal and see if I can update the code.

**Comment by waldeland** [comment]
Hi, I have updated the code now for python 3. Please let me know if you have any other troubles.
